target 'RNCocoaPodsExample' do
  platform :ios, '10.3'

  # React Native requirements
  pod 'yoga', path: './node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => './node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'GLog', :podspec => './node_modules/react-native/third-party-podspecs/GLog.podspec'
  # These seem to be the required subspecs, for some reason or other
  pod 'React', path: './node_modules/react-native', subspecs: [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ]

  pod 'BugsnagReactNative', path: './node_modules/bugsnag-react-native'
end
